### ISSUE TITLE
LIBRARY NOT FOUND IN PIP

### ISSUE THREAD

**Issue by Bukharee** [Flutterwave/Flutterwave-python-v3#6]
## System Information

 - Operating system: windows 10

**Comment by tobi-stephen** [comment]
similar error on MacOS

ERROR: Could not find a version that satisfies the requirement rave_python_v3 (from versions: none)
ERROR: No matching distribution found for rave_python_v3

**Comment by Bukharee** [comment]
@Official-kornelios  you need to pay attention to this issue and give us answer

**Comment by Corvus97** [comment]
Hello @tobi-stephen @Bukharee ,

Kindly be advised that the package has been archived in pip due to the heavy maintenance it is undergoing.

We will notify you once we move it away from our pip archives back to production.

Please bear with us.

Kind regards,
Cornelius

**Comment by Bukharee** [comment]
thanks @tobi-stephen for the reply cant wait.
